[alias]
b = "build"
br = "build --release"
c = "clean"
ck = "check"
d = "udeps"
e = "espflash flash --monitor"
er = "espflash flash --release --monitor"
g = "generate"
gn = "generate -a esp-rs/esp-template"
gs = "generate  esp-rs/esp-idf-template cargo"
i = "install"
f = "fix"
t = "test"
u = "update"
up = "install-update -a"
r = "run"
rr = "run --release"
s = "sort"
