[alias]
b = "build"
br = "build --release"
c = "check"
e = "espflash flash --monitor"
er = "espflash flash --release  --monitor"
g = "generate"
gn = "generate --git https://github.com/esp-rs/esp-template"
gs = "generate --git https://github.com/esp-rs/esp-idf-template cargo"
i = "install"
f = "fix"
t = "test"
u = "update"
r = "run"
rr = "run --release"
x = "clean"
